# Generated by Django 3.2.4 on 2023-10-25 11:45

from django.db import connection
from django.db.migrations import Migration, RunPython

from api.migrations._migration_helper import MigrationHelper

helper = MigrationHelper(connection)


def introduce_separate_data_gathering_functions(apps, schema_editor):
    helper.run_sql_files([
        '0130_rename_facilityindexnew_forward.sql',
        '0130_index_activity_reports_info.sql',
        '0130_index_approved_claim_ids.sql',
        '0130_index_approved_claim.sql',
        '0130_index_claim_info.sql',
        '0130_index_claim_sectors.sql',
        '0130_index_contrib_types.sql',
        '0130_index_contributors_count.sql',
        '0130_index_contributors_id.sql',
        '0130_index_contributors.sql',
        '0130_index_created_from_info.sql',
        '0130_index_extended_fields.sql',
        '0130_index_facility_addresses.sql',
        '0130_index_facility_list_items.sql',
        '0130_index_facility_locations.sql',
        '0130_index_facility_names.sql',
        '0130_index_facility_type.sql',
        '0130_index_lists.sql',
        '0130_index_native_language_name.sql',
        '0130_index_number_of_workers.sql',
        '0130_index_parent_company_id.sql',
        '0130_index_parent_company_name.sql',
        '0130_index_processing_type.sql',
        '0130_index_product_type.sql',
        '0130_index_sector.sql',
        '0130_index_facilities_by.sql',
        '0130_index_facilities.sql',
    ])


def revert_separate_data_gathering_functions(apps, schema_editor):
    raise Exception("130 migration is unrevertable")


class Migration(Migration):
    dependencies = [('api', '0129_delete_facility_index')]
    operations = [
        RunPython(introduce_separate_data_gathering_functions,
                  revert_separate_data_gathering_functions)
    ]
